name: CI
on:
  push:
    branches: [development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run jest tests
        run: yarn test
